server:
  port: 8888
spring:
  application:
    name: mall-gateway-sentinel-demo
  main:
    allow-bean-definition-overriding: true
  #配置nacos注册中心地址
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

    sentinel:
      transport:
        # 添加sentinel的控制台地址
        dashboard: localhost:10090
        # 指定应用与Sentinel控制台交互的端口，应用本地会起一个该端口占用的HttpServer
        #port: 8719

    gateway:
      # 是否开启网关
      enabled: true
      #设置路由：路由id、路由到微服务的uri、断言
      routes:
        - id: order_route  #路由ID，全局唯一，建议配合服务名
          uri: lb://mall-order  #lb 整合负载均衡器ribbon,loadbalancer
          predicates:
            - Path=/order/**

#        - id: user_route
#          uri: lb://mall-user  #lb 整合负载均衡器ribbon,loadbalancer
#          predicates:
#            - Path=/user/**







